### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by jadsalhani** [spxrogers/Alamofire-Gloss#1]

**Comment by spxrogers** [comment]
hey @jadsalhani, it's currently a WIP.
planning to have a new release out soon! I'll keep any relevant progress updated on this thread

**Comment by spxrogers** [comment]
https://github.com/spxrogers/Alamofire-Gloss/pull/6 <– this PR included essentially all of the migration to support Swift 3 (Alamofire 4 & Gloss 1). 

it's on master now and if all goes swimmingly with updating the pod, `Alamofire-Gloss 2.0.0` will be live soon

**Comment by spxrogers** [comment]
aaaaaaand, pod verification went swimmingly. version 2 is now pushed and live on cocoapods.
cc: @jadsalhani 

cheers 🎉

**Comment by jadsalhani** [comment]
@spxrogers Awesome congratz! Keep up the great work dude :D would be happy to start helping once I master Swift a bit more

Cheers! 🍺
