### ISSUE TITLE
'Decodable' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by luis-ct** [spxrogers/Alamofire-Gloss#13]
When I updated to xCode 9...

![screen shot 2017-09-15 at 13 24 10](https://user-images.githubusercontent.com/22480932/30480262-36485242-9a19-11e7-8f23-47295dd1b937.png)

**Comment by aurora14** [comment]
@luis-ct this is because Swift 4 introduces new JSON parsing protocols that also have a name Decodable. 

A quick workaround is to use Gloss.Decodable wherever this appears, or add the Gloss pod separately in your podfile and explicitly specify the Swift 4 branch.

**Comment by spxrogers** [comment]
hi @luis-ct, to build off of @aurora14's answer (thank you!)—these changes were fixed as of version 2.0.1 so if you update to the latest version you will no longer have this error.

**Comment by luis-ct** [comment]
@aurora14 @spxrogers Thanks for answering!
