### ISSUE TITLE
Gloss 2.0 support

### ISSUE THREAD

**Issue by nbattelli** [spxrogers/Alamofire-Gloss#14]
Hi @spxrogers! I would like to know if you will add support for Gloss 2.0 soon? :)

**Comment by spxrogers** [comment]
hi @nbattelli—Gloss's 2 release is still a beta.1 version.
i've been hesitant to support beta releases, but this one is a Swift 4 compatibility release so I will likely try to match the support. stay tuned in the next few days.

i'll update this issue accordingly.

**Comment by RJiryes** [comment]
Hey any updates on this?

**Comment by spxrogers** [comment]
working on this now.

**Comment by spxrogers** [comment]
[v3.0.0](https://github.com/spxrogers/Alamofire-Gloss/releases/tag/3.0.0) is released with Swift 4, Gloss 2, and AF 4.5 support. 

cheers.
