### ISSUE TITLE
Generic parameter 'T' could not be inferred

### ISSUE THREAD

**Issue by chandansingh5** [spxrogers/Alamofire-Gloss#15]
I am getting error "Generic parameter 'T' could not be inferred" in below line .

self.sections = Decoder.decode(decodableArrayForKey: "sections")(json)

Any guess how to fixed that. I am using Xcode 9.

**Comment by spxrogers** [comment]
hi @chandansingh5, it seems you are using the Gloss API directly and not AF-Gloss. 

you will get better help if you open an issue directly [there](https://github.com/hkellaway/Gloss/issues)
