### ISSUE TITLE
Alamofire+Gloss error -1

### ISSUE THREAD

**Issue by aurora14** [spxrogers/Alamofire-Gloss#8]
I've been trying to serialise a JSON array from the server, and have come across the error as titled in the subject.

To be more specific, I get the following: 

"JSON could not be serialized because of error:
The operation couldn’t be completed. (Alamofire+Gloss error -1.)"

Had a look at the documentation, but couldn't really see anything that would tell me why the error is occurring, or what it means, - wondering if you could guide me in the right direction?

**Comment by spxrogers** [comment]
hey @aurora14 sorry for this issue falling off my radar. 

this error is likely from a malformed JSON response and it fails deserializing the data. 
do you have an example of what you're trying to parse and i can help you debug the root cause?

**Comment by spxrogers** [comment]
closed due to inactivity. please reopen if future usage causes the same issue.

**Comment by nbattelli** [comment]
Hi @spxrogers How can I map the reason of the error? 
For example "missing key" or "expected String but got a Bool"

**Comment by spxrogers** [comment]
hi @nbattelli.
unfortunately, i do swallow the serialization error here: https://github.com/spxrogers/Alamofire-Gloss/blob/master/Source/Alamofire%2BGloss.swift#L156 

it wasn't a requirement at the time, so it wasn't a thought to bubble it up.
but i like the idea of providing it to `Alamofire-Gloss` users.

i've created #11 to track this item.

**Comment by spxrogers** [comment]
callers will now see the descriptive root cause of the error in version [2.1.0](https://github.com/spxrogers/Alamofire-Gloss/blob/master/CHANGELOG.md#210).

thanks for the feedback on `Moya-Gloss`! cc: @aurora14 @nbattelli
